/*
 * PrevEntryDialog.java
 *
 * Created on June 24, 2008, 1:25 PM
 */

package posdesktop;
import ordering.*;
import jpos.JposException;
import javax.swing.JOptionPane;
/**
 *
 * @author  angelchen
 */
public class EntryReceiptDialog extends javax.swing.JDialog {
    private POSPtrEntry en;
    /** Creates new form PrevEntryDialog */
    public EntryReceiptDialog(javax.swing.JDialog parent, boolean modal, POSPtrEntry theEn) {
        super(parent, modal);
        initComponents();
        this.en=theEn;
    }

    public void showReceipt(boolean heading){
        if(en==null) {
            displayArea.setText("Invalid Entry");
            reprintBtn.setEnabled(false);
        }
        else displayArea.setText(en.getReceiptStr(heading));
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        displayArea = new javax.swing.JTextArea();
        closeBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        reprintBtn = new javax.swing.JButton();
        restartBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        displayArea.setColumns(20);
        displayArea.setEditable(false);
        displayArea.setRows(5);
        jScrollPane1.setViewportView(displayArea);

        closeBtn.setFont(new java.awt.Font("SansSerif", 0, 24));
        closeBtn.setText("Close");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 18));
        jLabel1.setText("Receipt:");

        reprintBtn.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        reprintBtn.setText("Reprint Receipt");
        reprintBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reprintBtnActionPerformed(evt);
            }
        });

        restartBtn.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        restartBtn.setText("Restart Printer");
        restartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(reprintBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(restartBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(closeBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(closeBtn)
                    .addComponent(reprintBtn)
                    .addComponent(restartBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
// TODO add your handling code here:
    this.dispose();
}//GEN-LAST:event_closeBtnActionPerformed

private void reprintBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reprintBtnActionPerformed
// TODO add your handling code here:
    try{
    en.printToPrinter(MainProgram.getPtr());
    }catch(JposException e){
        JOptionPane.showMessageDialog(null, "Error printing:"+e.getMessage(),null,JOptionPane.ERROR_MESSAGE);
    }
}//GEN-LAST:event_reprintBtnActionPerformed

private void restartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartBtnActionPerformed
// TODO add your handling code here:
    boolean success=MainProgram.restartPrinter();
    if(!success){
        JOptionPane.showMessageDialog(this, "Failed to restart printer",null,JOptionPane.ERROR_MESSAGE);
    }else{
        JOptionPane.showMessageDialog(this, "Restart successful");
    }
}//GEN-LAST:event_restartBtnActionPerformed

/*
public javax.swing.JTextArea getDisplayArea(){
    return displayArea;
}
*/
    /**
    * @param args the command line arguments
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeBtn;
    private javax.swing.JTextArea displayArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton reprintBtn;
    private javax.swing.JButton restartBtn;
    // End of variables declaration//GEN-END:variables

}
