/*
 * NewCustomerDialog.java
 *
 * Created on May 23, 2008, 10:40 PM
 */

package posdesktop;
import javax.swing.*;
/**
 *
 * @author  angelchen
 */
public class NewCustomerDialog extends javax.swing.JDialog {
    SqlFunc sqlcus;
    
    /** Creates new form NewCustomerDialog */
    public NewCustomerDialog(RunGui parent, boolean modal, SqlFunc theSqlcus) {
        super(parent, modal);
        initComponents();
        this.sqlcus=theSqlcus;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        nameField = new javax.swing.JTextField();
        phoneField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressField = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create New Customer");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel2.setText("Name:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel1.setText("Telephone Number:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel3.setText("Address:");

        saveBtn.setFont(new java.awt.Font("Tahoma", 0, 24));
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        cancelBtn.setFont(new java.awt.Font("Tahoma", 0, 24));
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        nameField.setDocument(new FieldDocument(posdesktop.SqlFunc.NAME_MAX_LENGTH));
        nameField.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        phoneField.setDocument(new FieldDocument(posdesktop.SqlFunc.PHONE_LENGTH));
        phoneField.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N

        addressField.setColumns(20);
        addressField.setDocument(new FieldDocument(posdesktop.SqlFunc.ADDRESS_MAX_LENGTH));
        addressField.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        addressField.setLineWrap(true);
        addressField.setRows(5);
        jScrollPane1.setViewportView(addressField);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(phoneField)
                    .addComponent(nameField)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addComponent(saveBtn)
                .addGap(85, 85, 85)
                .addComponent(cancelBtn)
                .addGap(266, 266, 266))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveBtn)
                    .addComponent(cancelBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
    Object[] options = { "Yes", "No" };
    int cancel=JOptionPane.showOptionDialog(rootPane, "Are you sure you want to cancel?","Create New Customer",
            JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[1]);
    if(cancel==0) this.dispose();
}//GEN-LAST:event_cancelBtnActionPerformed

private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
// TODO add your handling code here:
    try{
       if(nameField.getText().length()==0){
        nameField.setText(sqlcus.getNextAvailableName());
       }
       phoneField.setText(SqlFunc.makePhoneValidIfPossible(phoneField.getText()));
        sqlcus.createCustomer(phoneField.getText(), nameField.getText(), addressField.getText());
    } catch (InvalidEntryException e){
        JOptionPane.showMessageDialog(rootPane,e.getMessage(),null,JOptionPane.ERROR_MESSAGE);
        return;
    } catch (DuplicateEntryException e){
        JOptionPane.showMessageDialog(rootPane,e.getMessage(),null,JOptionPane.ERROR_MESSAGE);
        return;
    } catch (Exception e){
        e.printStackTrace();
        return;
    }
    JOptionPane.showMessageDialog(rootPane,"Success creating new customer");
    this.dispose();
}//GEN-LAST:event_saveBtnActionPerformed

private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_nameFieldActionPerformed

    /**
    * @param args the command line arguments
    */
/* can't run by itself
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewCustomerDialog dialog = new NewCustomerDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
 */ 

/*
private int checkForDuplicate() throws Exception{
    if(sqlcus.searchbyPhone(phoneField.getText(), true).next()) return 1;
    else if(sqlcus.searchbyName(nameField.getText(), true).next()) return 2;
    else if(sqlcus.searchbyAddress(addressField.getText(), true).next()) return 3;
    return 0;
}
*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addressField;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField phoneField;
    private javax.swing.JButton saveBtn;
    // End of variables declaration//GEN-END:variables

}
